/* Copyright 2026 上海如静知华信息科技有限公司 · https://www.zhuatech.cn/ */
package cn.zhuatech.recruitai;
import org.junit.jupiter.api.*; import org.springframework.beans.factory.annotation.Autowired; import org.springframework.boot.webmvc.test.autoconfigure.AutoConfigureMockMvc; import org.springframework.boot.test.context.SpringBootTest; import org.springframework.http.MediaType; import org.springframework.test.web.servlet.MockMvc; import java.util.regex.*; import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.*; import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;
@SpringBootTest @AutoConfigureMockMvc class RecruitAiApiIntegrationTests {
    @Autowired MockMvc mvc; private String operatorToken; private String plannerToken;
    @BeforeEach void login()throws Exception{operatorToken=token("operator","Demo@2026");plannerToken=token("planner","Demo@2026");}
    private String token(String u,String p)throws Exception{String json=mvc.perform(post("/api/auth/login").contentType(MediaType.APPLICATION_JSON).content("{\"username\":\""+u+"\",\"password\":\""+p+"\"}")).andExpect(status().isOk()).andReturn().getResponse().getContentAsString();Matcher matcher=Pattern.compile("\\\"token\\\":\\\"([^\\\"]+)\\\"").matcher(json);if(!matcher.find())throw new AssertionError("登录响应中缺少 token");return matcher.group(1);}
    @Test void operatorCanReadShopfloorDashboard()throws Exception{mvc.perform(get("/api/shopfloor/dashboard").header("Authorization","Bearer "+operatorToken)).andExpect(status().isOk()).andExpect(jsonPath("$.success").value(true)).andExpect(jsonPath("$.data.metrics[0].label").value("在招职位"));}
    @Test void plannerCanReadWorkRecords()throws Exception{mvc.perform(get("/api/admin/work-orders").header("Authorization","Bearer "+plannerToken)).andExpect(status().isOk()).andExpect(jsonPath("$.data.length()").value(4));}
    @Test void operatorCanSubmitProductionReport()throws Exception{mvc.perform(post("/api/shopfloor/work-orders/1/reports").header("Authorization","Bearer "+operatorToken).contentType(MediaType.APPLICATION_JSON).content("{\"operationName\":\"治理评审\",\"goodQty\":2,\"defectQty\":1,\"remark\":\"证据完整\"}")).andExpect(status().isOk()).andExpect(jsonPath("$.message").value("候选人推进记录已提交")).andExpect(jsonPath("$.data.completedQty").value(18));}
    @Test void operatorCanAssessAiRisk()throws Exception{mvc.perform(post("/api/shopfloor/ai-risk-assessment").header("Authorization","Bearer "+operatorToken).contentType(MediaType.APPLICATION_JSON).content("{\"systemName\":\"授信助手\",\"useCase\":\"材料审阅\",\"autonomyLevel\":3,\"handlesPersonalData\":true,\"humanOversight\":false,\"externalImpact\":true,\"evaluated\":false,\"transparencyNotice\":false}")).andExpect(status().isOk()).andExpect(jsonPath("$.data.riskTier").value("HIGH")).andExpect(jsonPath("$.data.releaseDecision").value("BLOCK"));}
    @Test void operatorCanMatchCandidate()throws Exception{mvc.perform(post("/api/ai/candidate/match").header("Authorization","Bearer "+operatorToken).contentType(MediaType.APPLICATION_JSON).content("{\"candidate\":\"候选人A\",\"jobTitle\":\"Java工程师\",\"requiredSkills\":[\"Java\",\"MySQL\"],\"candidateSkills\":[\"Java\",\"Spring\"],\"years\":5}")).andExpect(status().isOk()).andExpect(jsonPath("$.data.matched[0]").value("Java")).andExpect(jsonPath("$.data.gaps[0]").value("MySQL"));}
    @Test void operatorCanAuditCandidateDecision()throws Exception{mvc.perform(post("/api/enterprise/recruitai/candidate-decision-audit").header("Authorization","Bearer "+operatorToken).contentType(MediaType.APPLICATION_JSON).content("{\"applicationId\":\"APP-100\",\"candidateId\":\"C-100\",\"criteriaVersion\":\"backend-v3\",\"decision\":\"ADVANCE\",\"criteria\":[{\"name\":\"Java经验\",\"jobRelated\":true,\"evidenceReference\":\"scorecard:1\",\"score\":85}],\"aiNoticeDelivered\":true,\"protectedAttributesExcluded\":true,\"humanDecisionMakerAssigned\":true,\"decisionRationale\":\"岗位能力证据满足阶段要求\",\"recommenderId\":\"engine\",\"reviewerId\":\"reviewer-a\",\"requiredScorecards\":1,\"completedScorecards\":1,\"accommodationRequested\":false,\"accommodationAddressed\":true,\"appealChannelReady\":true,\"retentionPolicyApplied\":true}"))
        .andExpect(status().isOk()).andExpect(jsonPath("$.data.decision").value("RECORDED"))
        .andExpect(jsonPath("$.data.auditKey").isNotEmpty());}
    @Test void anonymousRequestIsDenied()throws Exception{mvc.perform(get("/api/admin/dashboard")).andExpect(status().isForbidden());}
}
